### ISSUE TITLE
Tapping the picker on mobile opens the keyboard

### ISSUE THREAD

**Issue by mpstewart** [silent-lad/Vue2BaremetricsCalendar#1]
![4D57A2E1-F89A-4C07-805A-B95C9B1136F5](https://user-images.githubusercontent.com/2474237/66220823-b4d9c200-e69b-11e9-8b1a-97cb7b0ab7e2.png)

**Comment by silent-lad** [comment]
This issue was fixed with the last commit. The package version has also been bumped and published. Thanks for pointing this out 😃
